return {
    mod_name = {
        en = "RainbowFlame",
        sv = "RainbowFlame",
    },
    mod_description = {
        en = "Customize the Inferno staff and choose a fixed color preset for persistent enemy Soulblaze.",
        sv = "Anpassa Infernostaven och välj en fast färg för ihållande Själsbrand på fiender.",
    },
    enemy_color = { en = "Enemy Soulblaze color", sv = "Färg på fienders Själsbrand" },
    enemy_color_description = {
        en = "Selects the color of new persistent Soulblaze flames on enemies. Existing burns keep their current color, so apply Soulblaze again after changing this option. Original uses the game's normal color. This does not affect the staff.",
        sv = "Väljer färg för nya ihållande Själsbrandslågor på fiender. Befintliga bränder behåller sin färg, så applicera Själsbrand igen efter ett byte. Original använder spelets vanliga färg. Staven påverkas inte.",
    },
    enemy_color_original = { en = "Original", sv = "Original" },
    enemy_color_red = { en = "Red", sv = "Röd" },
    enemy_color_orange = { en = "Orange", sv = "Orange" },
    enemy_color_yellow = { en = "Yellow", sv = "Gul" },
    enemy_color_green = { en = "Green", sv = "Grön" },
    enemy_color_cyan = { en = "Cyan", sv = "Cyan" },
    enemy_color_blue = { en = "Blue", sv = "Blå" },
    enemy_color_violet = { en = "Violet", sv = "Violett" },
    enemy_color_pink = { en = "Pink", sv = "Rosa" },
    original_color = { en = "Original color", sv = "Originalfärg" },
    original_color_description = {
        en = "Uses the Inferno staff's original multi-color flame. This overrides Color, and the original appearance ignores Brightness. Rainbow takes priority while enabled. This does not affect enemy Soulblaze.",
        sv = "Använder Infernostavens ursprungliga flerfärgade låga. Detta åsidosätter Färg, och originalutseendet ignorerar Ljusstyrka. Regnbåge har företräde när den är aktiverad. Fienders Själsbrand påverkas inte.",
    },
    rainbow = { en = "Rainbow", sv = "Regnbåge" },
    rainbow_description = {
        en = "Cycles the staff flame through the full color wheel and its original multi-color appearance. Rainbow overrides Original color and Color while enabled. Turning it off restores your saved staff choice. Enemy Soulblaze presets are separate.",
        sv = "Växlar stavens låga genom hela färghjulet och dess ursprungliga flerfärgade utseende. Regnbåge åsidosätter Originalfärg och Färg när den är aktiverad. När den stängs av återställs ditt sparade stavval. Fiendernas Själsbrandspresets är separata.",
    },
    hue = { en = "Color", sv = "Färg" },
    hue_description = { en = "Selects the staff flame hue when Original color and Rainbow are both off. Color strength is always full. 0/360 red, 30 orange, 120 green, 180 cyan, 240 blue, and 270 violet. This does not affect enemy Soulblaze.", sv = "Väljer stavlågans nyans när både Originalfärg och Regnbåge är av. Färgstyrkan är alltid full. 0/360 rött, 30 orange, 120 grönt, 180 cyan, 240 blått och 270 violett. Fienders Själsbrand påverkas inte." },
    brightness = { en = "Brightness", sv = "Ljusstyrka" },
    brightness_description = { en = "Adjusts brightness for the staff's custom Color and Rainbow modes. 1 is normal; lower values darken the flame and higher values brighten it. Original color and enemy Soulblaze presets ignore this option.", sv = "Justerar ljusstyrkan för stavens egna Färg och Regnbåge. 1 är normalt; lägre värden mörkar lågan och högre värden gör den ljusare. Originalfärg och fiendernas Själsbrandspresets ignorerar detta val." },
    speed = { en = "Speed", sv = "Hastighet" },
    speed_description = { en = "Controls how quickly the staff's Rainbow mode changes color. 0.125 is the default and higher values cycle faster. This option has no effect while Rainbow is off and does not affect enemy Soulblaze.", sv = "Styr hur snabbt stavens Regnbågsläge växlar färg. 0.125 är standard och högre värden växlar snabbare. Valet har ingen effekt när Regnbåge är av och påverkar inte fienders Själsbrand." },
}
